Relative path for setup
Adding relative path to open( files) in setup. When installing I get an error due to relative path.

  Downloading goatools-0.7.6.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 2.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vg_81kde/goatools/setup.py", line 33, in <module>
        long_description=open("README.md").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'